#!/usr/bin/env bash

# Personal extension of .bashrc
# How to include : Just add in .bashrc the next line
#                        . ~/.my_bashrc
#

# MY ENV VARIABLES
SCRIPTS="$HOME/Scripts"
export SCRIPTS


GIT_STUFF="$HOME/GitStuff"
export GIT_STUFF

CURRENT_FROM_SOURCE="$HOME/fromSourceTools"
export CURRENT_FROM_SOURCE

#To new Boost home folder
#BOOST_ROOT="$CURRENT_FROM_SOURCE/boost-1-65/"
#export BOOST_ROOT

LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH

#To GraspIt
GRASPIT="$CURRENT_FROM_SOURCE/graspit"
#GRASPIT="$CURRENT_ROS_WS/src/grasp_synthesis"
export GRASPIT

#To Mimic Grasping
MIMIC_GRASPING_SERVER_ROOT="$HOME/clion_ws/mimic_grasping_api"
export MIMIC_GRASPING_SERVER_ROOT

MIMIC_HEARTBIT_CHECKER_ROOT="$HOME/lazarus_ws/6dmimic_hearbit_checker"
export MIMIC_HEARTBIT_CHECKER_ROOT

PATH=$PATH:/usr/local/cuda-11.4/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.4/lib64
export CUDADIR=/usr/local/cuda-11.4

export EDITOR=atom

#ROS STUFFS
export UBUNTU_VERSION=$(lsb_release -d | awk -F"\t" '{print $2}')
echo "»»"
echo "»» Ubuntu version: $UBUNTU_VERSION"

export HOST_HOSTNAME="msi"
export DISTROBOX_HOSTNAME_0="ubuntu_jazzy"

# ROS 1 STUFFS
if [[ $HOSTNAME == "$HOST_HOSTNAME" ]]; then

    export ROS_WS_PKG="$HOME/ros_ws"
    unset CMAKE_PREFIX_PATH

    #export CURRENT_ROS_WS="$ROS_WS_PKG/ws_common"
    #export CURRENT_ROS_WS="$ROS_WS_PKG/ws_drl"
    #export CURRENT_ROS_WS="$ROS_WS_PKG/ws_devices"
    #export CURRENT_ROS_WS="$ROS_WS_PKG/ws_graspit"
    export CURRENT_ROS_WS="$ROS_WS_PKG/ws_grasping"
    #export CURRENT_ROS_WS="$ROS_WS_PKG/ws_xweld"
    #export CURRENT_ROS_WS="$ROS_WS_PKG/ws_calibrations"
    #export CURRENT_ROS_WS="$ROS_WS_PKG/ws_missions"

    #source $ROS_1_DIR/setup.bash
    #source $CURRENT_ROS_WS/devel_release/setup.bash
    source $CURRENT_ROS_WS/devel_debug/setup.bash
    echo "»» Running ROS 1"
    echo "»» Current CMake Prefix Path:"
    echo "»»" $CMAKE_PREFIX_PATH

elif [[ $HOSTNAME == "$DISTROBOX_HOSTNAME_0" ]]; then
    unset CMAKE_PREFIX_PATH
    unset AMENT_PREFIX_PATH
    ROS_WS_PKG="$HOME/ros2_ws"
    export ROS_WS_PKG

    #para incluir os comando colcon
    source /usr/share/colcon_cd/function/colcon_cd.sh
    #para autocomplete do colcon
    source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash

    # Aqui define a hierarquia de workspaces.
    source /opt/ros/jazzy/setup.bash
      source $ROS_WS_PKG/sandbox_ws/install/local_setup.bash
      #source $ROS_WS_PKG/lab_ws/install/local_setup.bash

    export ROS_DOMAIN_ID="0"

    retorne_ultimo_ws_ros2() {
      local ws_install=$(echo "$AMENT_PREFIX_PATH" | awk -F ':' '{print $1}')
      local ws_root=$(dirname "$(dirname "$ws_install")")  # sobe 2 níveis
      echo "$ws_root"
    }

    #Configurando o colcon_cd para o ultimo ws da chain
    cd "$(retorne_ultimo_ws_ros2)" > /dev/null 2>&1
    colcon_cd --set > /dev/null 2>&1
    cd  > /dev/null 2>&1
    export COLCON_CD_ROOT="$(retorne_ultimo_ws_ros2)"

    colconsafebuild() {
      local ros_ws=$(retorne_ultimo_ws_ros2)

      if [[ -z "$ros_ws" ]]; then
        echo "🚫 Nenhuma workspace ativa detectada."
        return 1
      fi

      local current_dir=$(realpath .)
      local ws_dir=$(realpath "$ros_ws")

      if [[ "$current_dir" != "$ws_dir" ]]; then
        echo "🚫 Você não está na raiz da workspace ativa!"
        echo "➡️ Workspace ativa esperada: $ws_dir"
        echo "📍 Diretório atual: $current_dir"
        return 1
      fi

      echo "🔧 Build autorizado na workspace: $(basename "$ros_ws")"
      colcon build --symlink-install
    }


    # Função compacta para mostrar workspaces ROS 2
    ros2_ws_chain() {
      echo -n "»» Workspaces Chain: "

      if [ -z "$AMENT_PREFIX_PATH" ]; then
        echo "Nenhum workspace encontrado"
        return
      fi

      local ws_list=""
      local separator=" -> "

      # Extrai, simplifica e remove duplicatas dos caminhos de workspace
      for ws_path in $(echo "$AMENT_PREFIX_PATH" | tr ':' '\n' | sed 's|/install/.*$||' | sort | uniq); do
        if [[ $ws_path == "/opt/ros/"* ]]; then
          ws_list="${ws_list:+$ws_list$separator}$(basename $ws_path)(sys)"
        else
          ws_list="${ws_list:+$ws_list$separator}$(basename $ws_path)"
        fi
      done

      echo "$ws_list"
    }

    echo "»» Running ROS 2"
    #echo "»» Current Ament Prefix Path:"
    #echo "»»" $AMENT_PREFIX_PATH | tr ':' '\n'
    ros2_ws_chain
    echo "»» colcon_cd -> $(retorne_ultimo_ws_ros2)"

else
    echo "»»"
    echo "»» Running none ROS"
fi


# MY STUFFs
alias gws='cd $CURRENT_ROS_WS/src'
alias ggt='cd $GIT_STUFF'
alias gfs='cd $CURRENT_FROM_SOURCE'
alias bashporra='source /home/joaopedro/.bashrc'
alias vembash='atom /home/joaopedro/.my_bashrc'
#alias cade='dpkg -S' # indica: [responsável origem : caminho][válido para setups com apt-get]
#alias tenho='dpkg -l' # [válido para setups com apt-get]
alias instalar_dpkg='dpkg -i' # inserir nome do pacote .deb!
alias desinstalar_dpkg='dpkg -r' # inserir nome da aplicação/package
alias dependencias_do_meu_exec='ldd'
alias cade_rpm='rpm -qf'
alias amarelo='redshift -O 2500'
alias normal='redshift -x'
alias go_to_icons_folder='cd /home/joaopedro/.local/share/applications'
alias amarrar_processo='echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope'
#alias vemfriday_nuc='ssh user@172.16.10.1' #pass 5dpo
alias vem6dmimic='ssh mimic@172.16.47.113' #pass mimic
alias verificarkernellog='dmesg'
alias listarepositorio='atom /etc/apt/sources.list'
#alias para rules
alias vem_regras='cd /etc/udev/rules.d'
alias recarregar_rules='sudo udevadm control --reload-rules && sudo udevadm trigger'
alias lista_usb='lsusb'
alias monitore_imagem='podman logs -f'
alias dependenicas_ros='rosdep install -i --from-path src --rosdistro jazzy -y'
#verificar permissao da usb 'ls -l /dev/bus/usb/001/002' os número são fornecidos pelo comando anterior lsusb


# Alias functions (alias with parameters...)
# check with which gcc version and .bin of .so was copiled
# param: code file name
function qualgcc(){
  strings -a $1 | grep "GCC"
}
export -f qualgcc

 # check the device data info. Usefull to add rule at /etc/udev/rules.d
 # param: file name
function informacao_dispositivo(){
  udevadm info -a -p  $(udevadm info -q path -n $1)
}
export -f informacao_dispositivo

#check if a TCP or UDP port is in usage...
# param: port number
function uso_camada_transporte(){
  netstat -tulpn | grep $1
}
export -f uso_camada_transporte

#listen a TCP or UDP port...
# param1: ip
# param2: port number
function ouvir_camada_transporte(){
  netstat -tulpn | grep $1
  nc -lvu $1 $2
}
export -f uso_camada_transporte

# compile spec RPM file to code/project deployment
# param1: the path to spec file without "
function compilar_rpm(){
  rpmbuild -ba --clean $1
}

#change the version of a software in usage
# param1: software name
function troca_para_mim(){
    sudo update-alternatives --config $1
}

#change the version of a software in usage
# param1: path to install
# param2: software alias name
# param3: software path with version
# param3: priority number

function adiciona_para_mim(){
    sudo update-alternatives --install $1 $2 $3 $4
}


#change the version of a software in usage
# param1: path to private key
#Example : ~/.ssh/toGitHubOnly

function associar_ssh_key_git(){
    git config core.sshCommand "ssh -i $1"
}

# Docker run command to run everything needed to
# param1: docker image
# --rm apagar o estado
function docker_run_com_interface(){
  sudo docker run --gpus all --rm -ti --net=host --ipc=host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $XAUTHORITY:/tmp/.XAuthority -e XAUTHORITY=/tmp/.XAuthority --env="QT_X11_NO_MITSHM=1" $1 /bin/bash
}


# Indica se tenho o pacote passado como primeiro argumento
tenho() {
    echo "Procurando $1..."
    echo -e "\n »»»»»» Verificando apt/dpkg:"
    dpkg -l | grep "$1"
    echo -e "\n »»»»»» Verificando snap:"
    snap list | grep "$1"
}

# Indica onde esta o pacote passado como primeiro argumento
cade() {
   echo "»»»»»» Procurando $1..."
   echo -e "\nLocalizando via dpkg:"
   dpkg -S "$1" 2>/dev/null
   echo -e "\n»»»»»» Localizando via snap:"
   if snap list | grep -q "^$1"; then
       echo "Arquivos do snap: /var/lib/snapd/snaps/${1}_*.snap"
       echo "Montado em: /snap/$1"
   fi
}


# Related to Nvidea Configuration
alias desligarXserver='sudo systemctl stop lightdm.service'
alias ubuntuKernelVersion='echo "In Usage: "&&uname -r &&echo "Installed list: "&&dpkg --list | grep linux-image'
alias nvidiaInfo='nvcc --version&&nvidia-smi'

#Related to DHCP server
alias iniciarDHCP='systemctl start isc-dhcp-server'
alias pararDHCP='systemctl stop isc-dhcp-server'
alias reiniciarDHCP='systemctl restart isc-dhcp-server'
alias configurarDHCP='atom /etc/dhcp/dhcpd.conf& atom /etc/default/isc-dhcp-server'

alias vemVPN='sudo openvpn --config /home/joaopedro/VPN/inesctec_202103.ovpn'
alias meshlab='flatpak run net.meshlab.MeshLab'
alias ativar_agente_ssh='eval $(ssh-agent -s)'
alias liste_ssh_keys='ssh-add -l'


bind -x '"\C-k":my_kill' #to kill process
bind -x '"\C-b":catkin build' #to build ros pkgs

#unset CMAKE_PREFIX_PATH

#Bin-Picking
#Photoneo Sensor
export PHOXI_CONTROL_PATH=/opt/PhotoneoPhoXiControl-
#OpenRave
#source `/my/openraveinstall/bin/openrave-config --share-dir`/openrave.bash
#export PYTHONPATH=$PYTHONPATH:`openrave-config --python-dir`

#ROS_MASTER_URI=http://10.31.2.59:11311 #To Friday
#export ROS_IP=172.16.48.233

#ROS_MASTER_URI=http://192.168.214.25:11311 #To Friday
#export ROS_IP=10.40.217.221



echo "»» Current ROS_MASTER_URI Path:"
echo "»»" $ROS_MASTER_URI
echo "»» Current ROS_IP Path:"
echo "»»" $ROS_IP
echo "»»"



#cat /home/joaopedro/Desktop/Continuar
#alias code_name="command"

# ROSCONSOLE Output
export ROSCONSOLE_FORMAT='[${severity}] [${node}] [${time}]: ${message} | ${file}:${function}:${line}'
#export ROSCONSOLE_CONFIG_FILE='/home/joaopedro/.ros/config/rosconsole.config'
export ROSCONSOLE_STDOUT_LINE_BUFFERED=1
